"""Postgres dialect emission from the shared structured DDL ops (task 5).

render_postgres consumes exactly the same op objects as render_sqlite (AC-5
parity): the two renderers differ only in SQL, never in schema vocabulary.
These tests assert the dialect mapping (JSON -> JSONB, REAL -> DOUBLE PRECISION,
INTEGER PK -> GENERATED BY DEFAULT AS IDENTITY), the plpgsql trigger rewrite,
the contiguous shared version sequence, and store-tag scoping.
"""

import pytest

from mnemoseed.storage.drivers._migrations import (
    MIGRATIONS,
    AddColumn,
    AddTrigger,
    Column,
    CreateTable,
    latest_version,
    render_postgres,
    render_sqlite,
)


def test_pg_dialect_maps_neutral_kinds():
    op = CreateTable(
        store="graph",
        name="sample",
        columns=(
            Column("payload", "JSON", not_null=True),
            Column("weight", "REAL", not_null=True, default=0.5),
            Column("count", "INTEGER"),
        ),
    )
    sql = render_postgres(op)
    assert "payload JSONB NOT NULL" in sql
    assert "weight DOUBLE PRECISION NOT NULL DEFAULT 0.5" in sql
    assert "count INTEGER" in sql


def test_pg_integer_primary_key_generates_identity():
    op = CreateTable(
        store="meta",
        name="singleton",
        columns=(Column("id", "INTEGER", primary_key=True, default=1), Column("n", "INTEGER")),
    )
    assert "id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY" in render_postgres(op)


def test_pg_add_trigger_requires_pg_action():
    op = AddTrigger(
        store="meta",
        name="trg_x",
        timing="BEFORE",
        event="UPDATE",
        table="audit_log",
        action="BEGIN SELECT RAISE(ABORT, 'no'); END",
    )
    with pytest.raises(ValueError, match="pg_action"):
        render_postgres(op)


def test_pg_add_trigger_renders_function_and_trigger():
    op = AddTrigger(
        store="meta",
        name="trg_audit_no_update",
        timing="BEFORE",
        event="UPDATE",
        table="audit_log",
        action="irrelevant for pg",
        pg_action="RAISE EXCEPTION 'audit_log is append-only'",
    )
    sql = render_postgres(op)
    assert "CREATE OR REPLACE FUNCTION trg_audit_no_update() RETURNS trigger" in sql
    assert "LANGUAGE plpgsql" in sql
    assert "DROP TRIGGER IF EXISTS trg_audit_no_update ON audit_log;" in sql
    assert "CREATE TRIGGER trg_audit_no_update BEFORE UPDATE ON audit_log" in sql
    assert "EXECUTE FUNCTION trg_audit_no_update();" in sql


def _table_names() -> set[str]:
    return {op.name for m in MIGRATIONS for op in m.ops if isinstance(op, CreateTable)}


def test_both_renderers_consume_identical_op_sequence():
    """Every frozen migration op renders under both dialects without error."""
    for migration in MIGRATIONS:
        for op in migration.ops:
            assert render_sqlite(op)
            assert render_postgres(op)
            if isinstance(op, AddTrigger):
                assert op.pg_action


def test_table_sets_identical_across_dialects():
    assert {op.name for m in MIGRATIONS for op in m.ops if isinstance(op, CreateTable)} == (_table_names())


def test_shared_version_sequence_contiguous_forward_only():
    versions = [m.version for m in MIGRATIONS]
    assert versions == sorted(versions)
    assert versions == list(range(1, latest_version() + 1))


def test_store_tags_partition_ops():
    stores = {op.store for m in MIGRATIONS for op in m.ops}
    assert stores == {"graph", "meta"}
    assert any(m.applies_to("graph") for m in MIGRATIONS)
    assert any(m.applies_to("meta") for m in MIGRATIONS)


def test_v1_graph_tables_and_v2_pinned_column():
    graph_tables = {
        op.name for m in MIGRATIONS for op in m.ops if isinstance(op, CreateTable) and op.store == "graph"
    }
    assert graph_tables == {"nodes", "node_versions", "edges"}

    pinned = next(
        op for m in MIGRATIONS for op in m.ops if isinstance(op, AddColumn) and op.column.name == "pinned"
    )
    assert render_postgres(pinned) == (
        "ALTER TABLE nodes ADD COLUMN IF NOT EXISTS pinned INTEGER NOT NULL DEFAULT 0"
    )


def test_pg_node_versions_unique_and_token_cascade():
    node_versions = next(
        op for m in MIGRATIONS for op in m.ops if isinstance(op, CreateTable) and op.name == "node_versions"
    )
    assert "UNIQUE (node_id, version)" in render_postgres(node_versions)

    tokens = next(
        op for m in MIGRATIONS for op in m.ops if isinstance(op, CreateTable) and op.name == "tokens"
    )
    sql = render_postgres(tokens)
    assert "REFERENCES profiles(profile_id)" in sql
    assert "ON DELETE CASCADE" in sql


def test_pg_audit_log_identity_pk():
    audit = next(
        op for m in MIGRATIONS for op in m.ops if isinstance(op, CreateTable) and op.name == "audit_log"
    )
    assert "id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY" in render_postgres(audit)
