"""AC-5 migration parity between the SQLite and Postgres dialects.

The shared, store-tagged migration sequence (``_migrations.MIGRATIONS``) is the
single source of truth: the same version sequence, the same v1 -> v2 forward
upgrade, and the same column model must materialize on both dialects. The
offline arm proves this on rendered DDL and on a live SQLite database; the
Postgres arm (skipped cleanly when ``MNEMOSEED_TEST_PG_DSN`` is absent) mirrors
the same checks against a live server and compares the real catalogs.

Per PRD-08 the stores live in separate schemas (D6), so graph and meta never
share one ``schema_version`` table.
"""

from __future__ import annotations

import json
import re
import sqlite3
import uuid
from collections.abc import Sequence
from typing import Any

import psycopg
from _support import make_pref, require_pg
from psycopg.rows import dict_row

from mnemoseed.schema.graph import GraphNode
from mnemoseed.storage.drivers._migrations import (
    _PG_KINDS,
    _SQLITE_KINDS,
    MIGRATIONS,
    SCHEMA_VERSION_TABLE,
    AddColumn,
    AddTrigger,
    Column,
    CreateIndex,
    CreateTable,
    apply_migrations,
    apply_postgres_migrations,
    current_postgres_schema_version,
    current_schema_version,
    latest_version,
    render_postgres,
    render_sqlite,
)
from mnemoseed.storage.drivers._time import iso8601_utc

# ---------------------------------------------------------------- ddl parsing


def _table_body(sql: str) -> str:
    """Body of a ``CREATE TABLE ... (...)`` statement (paren-depth aware)."""
    start = sql.index("(")
    depth = 0
    for i in range(start, len(sql)):
        if sql[i] == "(":
            depth += 1
        elif sql[i] == ")":
            depth -= 1
            if depth == 0:
                return sql[start + 1 : i]
    raise AssertionError(f"unbalanced CREATE TABLE: {sql}")


def _split_top_level(body: str) -> list[str]:
    clauses: list[str] = []
    current: list[str] = []
    depth = 0
    i = 0
    while i < len(body):
        ch = body[i]
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == "," and depth == 0:
            clauses.append("".join(current).strip())
            current = []
            i += 1
            if i < len(body) and body[i] == " ":
                i += 1
            continue
        current.append(ch)
        i += 1
    if current:
        clauses.append("".join(current).strip())
    return clauses


def _parse_column_clause(clause: str) -> tuple[str, str, bool, bool, bool, bool]:
    """(name, kind, has_pk, has_not_null, has_default, has_references)."""
    upper = clause.upper()
    name, rest = clause.split(maxsplit=1)
    if "DOUBLE PRECISION" in upper:
        kind = "DOUBLE PRECISION"
    else:
        kind = rest.split(maxsplit=1)[0]
    has_pk = "PRIMARY KEY" in upper
    has_nn = "NOT NULL" in upper
    has_default = "DEFAULT" in upper and "GENERATED BY DEFAULT AS IDENTITY" not in upper
    has_ref = "REFERENCES" in upper
    return (name, kind, has_pk, has_nn, has_default, has_ref)


def _parse_create_table(sql: str) -> list[tuple[str, str, bool, bool, bool, bool]]:
    columns = (
        _parse_column_clause(cl)
        for cl in _split_top_level(_table_body(sql))
        if not cl.upper().startswith("UNIQUE")
    )
    return [c for c in columns if c]


def _parse_index(sql: str) -> tuple[bool, str, str, tuple[str, ...]]:
    match = re.search(r"CREATE (UNIQUE )?INDEX IF NOT EXISTS (\w+) ON (\w+) \(([^)]+)\)", sql)
    assert match is not None, sql
    unique, name, table, columns = match.groups()
    return bool(unique), name, table, tuple(part.strip() for part in columns.split(","))


# ------------------------------------------------------- shared-op schema parity


def _expected_sqlite_kind(kind: str) -> str:
    return _SQLITE_KINDS[kind]


def _expected_pg_kind(kind: str) -> str:
    return _PG_KINDS[kind]


def test_version_sequences_identical_on_both_dialects() -> None:
    """The dialect-agnostic sequence IS the parity baseline (graph 1,2,5; meta 1,3,4,6)."""
    assert latest_version() == 6
    graph_versions = sorted(m.version for m in MIGRATIONS if m.applies_to("graph"))
    meta_versions = sorted(m.version for m in MIGRATIONS if m.applies_to("meta"))
    assert graph_versions == [1, 2, 5]
    assert meta_versions == [1, 3, 4, 6]
    assert len(MIGRATIONS) == latest_version()


def test_create_tables_render_zero_diff_from_shared_ops() -> None:
    """Both dialects materialise the same column model; only the alias map differs."""
    for migration in MIGRATIONS:
        for op in migration.ops:
            if not isinstance(op, CreateTable):
                continue
            sqlite_cols = _parse_create_table(render_sqlite(op))
            pg_cols = _parse_create_table(render_postgres(op))
            assert len(sqlite_cols) == len(pg_cols) == len(op.columns)
            for index, column in enumerate(op.columns):
                s, p = sqlite_cols[index], pg_cols[index]
                # identity is the same neutral column, in the same position
                assert s[0] == p[0] == column.name
                # kind: each dialect lands exactly where its documented map sends it
                assert s[1] == _expected_sqlite_kind(column.kind)
                assert p[1] == _expected_pg_kind(column.kind)
                # dialect-independent flags agree between the two parses
                assert s[2] == p[2] == column.primary_key  # has pk
                assert s[3] == p[3] == column.not_null  # not null
                assert s[5] == p[5] == (column.references is not None)  # references
                # default presence: sqlite renders any non-None; pg omits it for
                # integer PKs (identity supplies the value).
                assert s[4] == (column.default is not None)
                assert p[4] == (
                    column.default is not None and not (column.primary_key and column.kind == "INTEGER")
                )


def test_indexes_render_zero_diff() -> None:
    for migration in MIGRATIONS:
        for op in migration.ops:
            if not isinstance(op, CreateIndex):
                continue
            s = _parse_index(render_sqlite(op))
            p = _parse_index(render_postgres(op))
            assert s == (op.unique, op.name, op.table, op.columns)
            assert p == s


def test_add_columns_render_zero_diff() -> None:
    for migration in MIGRATIONS:
        for op in migration.ops:
            if not isinstance(op, AddColumn):
                continue
            sqlite_clause = render_sqlite(op).split("ADD COLUMN ")[1]
            pg_clause = render_postgres(op).split("ADD COLUMN ", 1)[1]
            if pg_clause.upper().startswith("IF NOT EXISTS "):
                pg_clause = pg_clause[len("IF NOT EXISTS ") :]
            s = _parse_column_clause(sqlite_clause)
            p = _parse_column_clause(pg_clause)
            assert s[0] == p[0] == op.column.name
            assert s[1] == _expected_sqlite_kind(op.column.kind)
            assert p[1] == _expected_pg_kind(op.column.kind)
            assert s[2] == p[2] == op.column.primary_key
            assert s[3] == p[3] == op.column.not_null


def test_triggers_exist_on_both_dialects() -> None:
    """The append-only audit barrier is a parity item, not a sqlite extra."""
    for migration in MIGRATIONS:
        for op in migration.ops:
            if not isinstance(op, AddTrigger):
                continue
            sql = render_sqlite(op)
            pg = render_postgres(op)
            assert op.table in sql and op.timing in sql and op.event in sql
            assert op.table in pg and op.timing in pg and op.event in pg
            assert op.pg_action, f"{op.name}: pg_action is required for the Postgres arm"


# ------------------------------------------------------------ sqlite arm (offline)


def _column_names(conn: sqlite3.Connection, table: str) -> list[str]:
    return [str(row[1]) for row in conn.execute(f"PRAGMA table_info({table})")]


def _node_row_mirror(node: GraphNode) -> dict[str, object]:
    """The exact v1 nodes row shape the driver's ``_node_row`` produces."""
    return {
        "node_id": node.node_id,
        "node_type": node.node_type.value,
        "profile_id": node.profile_id,
        "payload": json.dumps(node.props),
        "entities": json.dumps(node.entities),
        "confidence": node.confidence,
        "decay_weight": node.decay_weight,
        "never_decay": int(node.never_decay),
        "conflict_flag": int(node.conflict_flag),
        "conflict_group": node.conflict_group,
        "needs_reconcile": int(node.needs_reconcile),
        "pending_consolidation": int(node.pending_consolidation),
        "peripheral_gaps": int(node.peripheral_gaps),
        "valid_from": iso8601_utc(node.valid_from),
        "valid_to": iso8601_utc(node.valid_to) if node.valid_to is not None else None,
        "last_reinforced": iso8601_utc(node.last_reinforced),
        "hit_count": node.hit_count,
        "last_hit_at": iso8601_utc(node.last_hit_at) if node.last_hit_at is not None else None,
        "reinforce_count": node.reinforce_count,
        "cognitive_tier": node.cognitive_tier,
        "provenance": node.provenance.model_dump_json(),
        "created_at": iso8601_utc(node.created_at),
        "updated_at": iso8601_utc(node.updated_at),
        "version": node.version,
        "prev_version_id": node.prev_version_id,
    }


def _insert(conn: sqlite3.Connection, table: str, row: dict[str, object]) -> None:
    columns = ", ".join(row)
    placeholders = ", ".join("?" * len(row))
    conn.execute(f"INSERT INTO {table} ({columns}) VALUES ({placeholders})", list(row.values()))


def _snapshot(conn: sqlite3.Connection, tables: Sequence[str]) -> dict[str, list[dict[str, object]]]:
    """Row-by-row copy of whole tables for byte-level preservation checks.

    A table that does not exist yet in the store (e.g. the v6 ``users`` table
    on a v1 meta install) snapshots as ``[]`` so the before/after comparison
    stays total: it was empty before the upgrade and stays empty after it
    (v6 has no backfill).
    """
    snap: dict[str, list[dict[str, object]]] = {}
    for table in tables:
        exists = conn.execute(
            "SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ?", (table,)
        ).fetchone()
        if exists is None:
            snap[table] = []
            continue
        rows = conn.execute(f"SELECT * FROM {table}").fetchall()
        snap[table] = [dict(row) for row in rows]
    return snap


def _load_v1_sqlite() -> tuple[sqlite3.Connection, sqlite3.Connection]:
    """Seed a v1 install: separate graph/meta stores (D6 separate files)."""
    # autocommit mode, matching the drivers: DML must not open an implicit
    # transaction that later collides with the migration runner's BEGIN IMMEDIATE
    graph = sqlite3.connect(":memory:", isolation_level=None)
    graph.row_factory = sqlite3.Row
    meta = sqlite3.connect(":memory:", isolation_level=None)
    meta.row_factory = sqlite3.Row
    assert apply_migrations(graph, "graph", target=1) == 1
    assert apply_migrations(meta, "meta", target=1) == 1

    node = make_pref(node_id="mv1", entities=["ui", "theme"])
    _insert(graph, "nodes", _node_row_mirror(node))
    _insert(
        graph,
        "node_versions",
        {
            "node_id": "mv1",
            "version": 1,
            "profile_id": node.profile_id,
            "valid_from": iso8601_utc(node.valid_from),
            "valid_to": None,
            "superseded_by": None,
            "changed_at": iso8601_utc(node.updated_at),
            "payload": json.dumps(node.props),
        },
    )
    _insert(
        graph,
        "edges",
        {
            "id": "e1",
            "src": "mv1",
            "dst": "mv2",
            "rel": "evidenced_by",
            "weight": 1.0,
            "profile_id": node.profile_id,
            "provenance": json.dumps({"asserted_by": "contract-agent"}),
            "created_at": iso8601_utc(node.updated_at),
        },
    )
    _insert(
        meta,
        "profiles",
        {"profile_id": "u1", "display_name": "Uma", "created_at": iso8601_utc(node.updated_at)},
    )
    _insert(
        meta,
        "tokens",
        {
            "token_id": "tok-1",
            "profile_id": "u1",
            "scopes": json.dumps(["graph:read"]),
            "issued_at": iso8601_utc(node.updated_at),
            "expires_at": None,
            "revoked": 0,
        },
    )
    _insert(
        meta,
        "config",
        {
            "key": "theme",
            "value": json.dumps({"mode": "dark"}),
            "version": 1,
            "updated_at": iso8601_utc(node.updated_at),
        },
    )
    # score_pool singleton exists via defaults; insert id=1 explicitly
    _insert(
        meta,
        "score_pool",
        {
            "id": 1,
            "balance": 0.0,
            "watermark_start": 0,
            "watermark_end": 0,
            "last_event_start": 0,
            "last_event_end": 0,
        },
    )
    _insert(
        meta,
        "audit_log",
        {
            "id": 1,
            "actor": "alice",
            "action": "insert",
            "detail": json.dumps({"n": 1}),
            "at": iso8601_utc(node.updated_at),
        },
    )
    _insert(
        meta,
        "dream_runs",
        {
            "run_id": "run-1",
            "session_id": "s1",
            "turn_start": 1,
            "turn_end": 3,
            "model_id": "claude",
            "started_at": iso8601_utc(node.updated_at),
            "finished_at": None,
            "tokens": 42,
            "cost": 0.0042,
            "interrupted": 0,
            "dropped_count": 0,
        },
    )
    return graph, meta


_GRAPH_TABLES = ("nodes", "node_versions", "edges")
_META_TABLES = (
    "profiles",
    "tokens",
    "score_pool",
    "config",
    "audit_log",
    "dream_runs",
    "users",
)


def test_sqlite_v1_to_head_forward_migration_preserves_data() -> None:
    """A real file at v1 upgrades to head: column added, every row survives."""
    graph, meta = _load_v1_sqlite()
    assert "pinned" not in _column_names(graph, "nodes")
    graph_before = _snapshot(graph, _GRAPH_TABLES)
    meta_before = _snapshot(meta, _META_TABLES)
    assert current_schema_version(graph, "graph") == 1
    assert current_schema_version(meta, "meta") == 1

    # forward migration: graph advances to 5, meta to 6 (v2/v5 are graph-only,
    # v6 is meta-only: identity users table + hashed token column)
    assert apply_migrations(graph, "graph") == 5
    assert apply_migrations(meta, "meta") == 6
    assert current_schema_version(graph, "graph") == 5
    assert current_schema_version(meta, "meta") == 6

    assert "pinned" in _column_names(graph, "nodes")
    assert "promotion_status" in _column_names(graph, "nodes")
    row = dict(
        graph.execute("SELECT pinned, promotion_status, payload FROM nodes WHERE node_id = 'mv1'").fetchone()
    )
    assert row["pinned"] == 0  # NOT NULL DEFAULT 0 backfills the existing row
    assert row["promotion_status"] == "promoted"  # v5 default back-compat on the same row
    assert json.loads(row["payload"]) == make_pref(node_id="mv1").props  # byte-identical payload

    graph_after = _snapshot(graph, _GRAPH_TABLES)
    meta_after = _snapshot(meta, _META_TABLES)
    assert _project_without_deltas(graph_after["nodes"]) == graph_before["nodes"]
    for table in ("node_versions", "edges"):
        assert graph_after[table] == graph_before[table], f"row drift in {table} across v1->v3"
    for table in _META_TABLES:
        # v6 adds the nullable token_hash column; the legacy v1 token row is
        # preserved byte-for-byte, projected without the new (empty) column.
        rows = [r for r in meta_after[table]]
        if table == "tokens":
            rows = [{k: v for k, v in r.items() if k != "token_hash"} for r in rows]
        assert rows == meta_before[table], f"row drift in {table} across v1->head"

    # v3 supersedes the legacy score_pool: the new per-profile table exists,
    # empty (no data migration), and the old singleton row is untouched.
    assert _column_names(meta, "profile_score_pool") == [
        "profile_id",
        "balance",
        "watermark_start",
        "watermark_end",
        "last_event_start",
        "last_event_end",
    ]
    empty = meta.execute("SELECT COUNT(*) FROM profile_score_pool").fetchone()
    assert int(empty[0]) == 0
    legacy = dict(meta.execute("SELECT id, balance FROM score_pool").fetchone())
    assert legacy["id"] == 1
    assert legacy["balance"] == 0.0

    # v4 dream_token_ledger exists, empty (no backfill: it is born empty)
    assert _column_names(meta, "dream_token_ledger") == ["profile_id", "year_month", "tokens"]
    unique_constraint = meta.execute(
        "SELECT sql FROM sqlite_master WHERE type = 'table' AND name = 'dream_token_ledger'"
    ).fetchone()
    assert "UNIQUE (profile_id, year_month)" in unique_constraint[0]

    # v6 identity: the users table exists (empty after upgrade — no backfill),
    # and the legacy tokens row gained a nullable token_hash (NULL for v1 era).
    assert _column_names(meta, "users") == ["user_id", "username", "password_hash", "role", "created_at"]
    user_row = dict(meta.execute("SELECT token_hash FROM tokens WHERE token_id = 'tok-1'").fetchone())
    assert user_row["token_hash"] is None  # pre-v6 tokens hold no hash (blessed empty)

    # tracker advanced one step per graph/meta delta (v2/v5 graph, v4/v6 meta)
    graph_versions = [int(r[0]) for r in graph.execute(f"SELECT version FROM {SCHEMA_VERSION_TABLE}")]
    meta_versions = [int(r[0]) for r in meta.execute(f"SELECT version FROM {SCHEMA_VERSION_TABLE}")]
    assert sorted(graph_versions) == [1, 2, 5]
    assert sorted(meta_versions) == [1, 3, 4, 6]


def _project_without_deltas(rows: list[dict[str, object]]) -> list[dict[str, object]]:
    """Drop the post-v1 migration delta columns (pinned v2, promotion_status v5)."""
    deltas = {"pinned", "promotion_status"}
    return [{k: v for k, v in row.items() if k not in deltas} for row in rows]


# -------------------------------------------------------------- postgres arm (live)


def _pg_conn(dsn: str) -> Any:
    return psycopg.connect(dsn, row_factory=dict_row)


def _pg_insert(conn: Any, schema: str, table: str, row: dict[str, object]) -> None:
    columns = ", ".join(row)
    placeholders = ", ".join("%s" for _ in row)
    conn.execute(
        f"INSERT INTO {schema}.{table} ({columns}) VALUES ({placeholders})",
        list(row.values()),
    )


def _pg_snapshot(conn: Any, schema: str, table: str) -> list[dict[str, object]]:
    return [dict(r) for r in conn.execute(f"SELECT * FROM {schema}.{table}").fetchall()]


def test_postgres_v1_to_head_forward_migration_preserves_data() -> None:
    """Live Postgres mirrors the sqlite arm: v1 data survives the head upgrade."""
    dsn = require_pg()
    graph_schema = f"par_g_{uuid.uuid4().hex[:8]}"
    meta_schema = f"par_m_{uuid.uuid4().hex[:8]}"
    conn = _pg_conn(dsn)

    with conn.transaction():
        assert apply_postgres_migrations(conn, "graph", target=1, schema=graph_schema) == 1
        assert apply_postgres_migrations(conn, "meta", target=1, schema=meta_schema) == 1
        assert current_postgres_schema_version(conn, "graph", schema=graph_schema) == 1
        assert "pinned" not in [c["column_name"] for c in _pg_columns(conn, graph_schema, "nodes")]

        node = make_pref(node_id="mv1", entities=["ui", "theme"])
        node_row = _node_row_mirror(node)
        _pg_insert(conn, graph_schema, "nodes", node_row)
        _pg_insert(
            conn,
            graph_schema,
            "node_versions",
            {
                "node_id": "mv1",
                "version": 1,
                "profile_id": node.profile_id,
                "valid_from": iso8601_utc(node.valid_from),
                "valid_to": None,
                "superseded_by": None,
                "changed_at": iso8601_utc(node.updated_at),
                "payload": json.dumps(node.props),
            },
        )
        before_nodes = _pg_snapshot(conn, graph_schema, "nodes")

        assert apply_postgres_migrations(conn, "graph", schema=graph_schema) == 5
        assert apply_postgres_migrations(conn, "meta", schema=meta_schema) == 6
        assert current_postgres_schema_version(conn, "graph", schema=graph_schema) == 5
        assert current_postgres_schema_version(conn, "meta", schema=meta_schema) == 6
        pool_columns = [c["column_name"] for c in _pg_columns(conn, meta_schema, "profile_score_pool")]
        assert pool_columns == [
            "profile_id",
            "balance",
            "watermark_start",
            "watermark_end",
            "last_event_start",
            "last_event_end",
        ]
        empty = conn.execute("SELECT COUNT(*) AS n FROM " + meta_schema + ".profile_score_pool").fetchone()
        assert empty is not None and int(empty["n"]) == 0
        ledger_columns = [c["column_name"] for c in _pg_columns(conn, meta_schema, "dream_token_ledger")]
        assert ledger_columns == ["profile_id", "year_month", "tokens"]
        user_columns = [c["column_name"] for c in _pg_columns(conn, meta_schema, "users")]
        assert user_columns == ["user_id", "username", "password_hash", "role", "created_at"]
        token_hash_columns = [c["column_name"] for c in _pg_columns(conn, meta_schema, "tokens")]
        assert "token_hash" in token_hash_columns

        columns = [c["column_name"] for c in _pg_columns(conn, graph_schema, "nodes")]
        assert "pinned" in columns
        assert "promotion_status" in columns
        after_nodes = _pg_snapshot(conn, graph_schema, "nodes")
        assert [
            {k: v for k, v in r.items() if k not in ("pinned", "promotion_status")} for r in after_nodes
        ] == before_nodes
        preserved = after_nodes[0]
        assert preserved["pinned"] == 0
        assert preserved["promotion_status"] == "promoted"
        clean_payload = preserved["payload"]
        if isinstance(clean_payload, str):  # sqlite TEXT arm
            clean_payload = json.loads(clean_payload)
        assert clean_payload == node.props


def _neutral_head_columns() -> dict[str, list[Column]]:
    """Neutral columns each table must have at head: CreateTable base plus the
    AddColumn deltas that later migrations apply (pinned v2 and
    promotion_status v5 on graph.nodes)."""
    columns_by_table: dict[str, list[Column]] = {}
    for migration in MIGRATIONS:
        for op in migration.ops:
            if isinstance(op, CreateTable):
                columns_by_table.setdefault(op.name, []).extend(op.columns)
            elif isinstance(op, AddColumn):
                columns_by_table.setdefault(op.table, []).append(op.column)
    return columns_by_table


def test_live_catalog_zero_diff_against_shared_ops() -> None:
    """Introspect the real catalogs; both match the neutral column spec (zero diff)."""
    dsn = require_pg()
    graph_db = sqlite3.connect(":memory:", isolation_level=None)  # store isolation (D6)
    graph_db.row_factory = sqlite3.Row
    meta_db = sqlite3.connect(":memory:", isolation_level=None)
    meta_db.row_factory = sqlite3.Row
    apply_migrations(graph_db, "graph")
    apply_migrations(meta_db, "meta")

    graph_schema = f"par_g_{uuid.uuid4().hex[:8]}"
    meta_schema = f"par_m_{uuid.uuid4().hex[:8]}"
    conn = _pg_conn(dsn)
    with conn.transaction():
        apply_postgres_migrations(conn, "graph", schema=graph_schema)
        apply_postgres_migrations(conn, "meta", schema=meta_schema)

    for table_name, columns in _neutral_head_columns().items():
        emb = graph_db if table_name in set(_GRAPH_TABLES) else meta_db
        target_pg = graph_schema if table_name in set(_GRAPH_TABLES) else meta_schema
        sqlite_cols = {
            (str(c[1]).strip('"'), bool(c[3]), bool(c[5]))  # (name, notnull, pk)
            for c in emb.execute(f"PRAGMA table_info({table_name})").fetchall()
        }
        pg_cols = {
            (str(c["column_name"]), c["is_nullable"] == "NO", c["has_pk"])
            for c in _pg_columns(conn, target_pg, table_name)
        }
        expected = {(col.name, col.not_null, bool(col.primary_key)) for col in columns}
        # sqlite reports exactly the declared flags; Postgres makes every PK
        # physically NOT NULL (identity polls additionally turn NOT NULL on).
        expected_pg = {
            (col.name, col.not_null or bool(col.primary_key), bool(col.primary_key)) for col in columns
        }
        assert sqlite_cols == expected, f"sqlite {table_name} diverges from neutral ops"
        assert pg_cols == expected_pg, f"postgres {table_name} diverges from neutral ops"


def _pg_columns(conn: Any, schema: str, table: str) -> list[dict[str, object]]:
    columns = [
        dict(r)
        for r in conn.execute(
            "SELECT column_name, data_type, is_nullable, column_default "
            "FROM information_schema.columns "
            "WHERE table_schema = %s AND table_name = %s ORDER BY ordinal_position",
            (schema, table),
        ).fetchall()
    ]
    pk_names = {
        str(r["attname"])
        for r in conn.execute(
            "SELECT a.attname FROM pg_index i "
            "JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey) "
            "WHERE i.indrelid = %s::regclass AND i.indisprimary",
            (f"{schema}.{table}",),
        ).fetchall()
    }
    return [dict(col, has_pk=col["column_name"] in pk_names) for col in columns]
